Add docker analyzerDatabase healthcheck and docker analyzer venv

diff --git a/apps/analyzer/Dockerfile b/apps/analyzer/Dockerfile
--- a/apps/analyzer/Dockerfile
+++ b/apps/analyzer/Dockerfile
@@ -5,13 +5,17 @@ FROM python:3.11-slim-buster
 WORKDIR /app
 
 COPY . .
-
-COPY pyproject.toml poetry.lock ./
+RUN rm -rf .venv
+# COPY pyproject.toml poetry.lock ./
 
 #Install Python and Pipx
 RUN python3 -m pip install --no-cache-dir --upgrade pip && \
     pip install --no-cache-dir pipx && \
     pipx ensurepath
+
+# Install PostgreSQL client
+RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && \
+    apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Install Poetry with pipx
 RUN pipx install poetry
@@ -20,9 +24,17 @@ RUN pipx install poetry
 ENV PATH="/root/.local/bin:$PATH"
 
 #Install dependencies outside of the venv
-RUN poetry config virtualenvs.create false
-RUN poetry install --no-interaction --no-ansi --verbose --no-root
+# RUN poetry config virtualenvs.create true
+RUN poetry config virtualenvs.create true
+RUN poetry config virtualenvs.in-project true
+RUN poetry install --no-interaction --no-ansi --verbose || echo "Poetry installation failed"
+# RUN poetry install --no-interaction --no-ansi --verbose --no-root
+
+# Activate virtual environment and set it in PATH
+ENV PATH="/app/.venv/bin:$PATH"
+
+# RUN python3 -m pip install --no-cache-dir flask
 
 #Copy the remaining code
-COPY . .
+# COPY . .
 
